### ISSUE TITLE
Wrong tiles URL under Windows

### ISSUE THREAD

**Issue by kmandov** [mojodna/tessera#23]
Hi,

I am using tessera under Windows. I use it to serve local source file like this:
```
> tessera tmsource:\\.\sofia-source.tm2source --p 8500
```
In Mapbox Studio I specify the tilejson url generated by Tessera:
```
http://localhost:8500/index.json
```
At this point,  I can see Mapbox Studio calling Tessera, however the tile url has an additional / so it always ends in 404 error:
```
GET //14/8205/8173.pbf 404 1.314 ms - 30
GET //14/8206/8173.pbf 404 1.998 ms - 30
```

I believe the reason for this behavior is the url of the tiles. It is: 
```
"tiles":["http://localhost:8500\\\\{z}\\{x}\\{y}.pbf"]
```

while it should be:
```
"tiles":["http://localhost:8500/{z}/{x}/{y}.pbf""]
```

I can fix the problem If I remove the use of `Path.normalize` from the callback that generates `index.json` in `app.js`:
```
        var uri = "http://" + req.headers.host +
                                   tilePath.replace("{format}",
                                          getExtension(info.format));
```

Regards,
Kiril

**Comment by mojodna** [comment]
Good find.  Looks like `path.normalize` uses platform-dependent delimiters, hence the backslashes showing up.

**Comment by mojodna** [comment]
`path.normalize` was being used to eliminate repeated `/`s. Now it uses a non-platform-dependent way of doing that.
