### ISSUE TITLE
Unable to use two layers in project.yml

### ISSUE THREAD

**Issue by flemmens** [mojodna/tessera#25]
I have two custom layers saved in pbf mbtiles. Everything is working fine if I use a single layer:
source: "mbtiles:/home/data/a.mbtiles"

However, when I try to use two layers, I got the following error message:
source: "mbtiles:/home/data/a.mbtiles,mbtiles:/home/data/b.mbtiles"
Error: SQLITE_CANTOPEN: unable to open database file

I tried several writing:
source: "mbtiles:/home/data/a.mbtiles,/home/data/b.mbtiles"
source: "mbtiles:/home/data/a.mbtiles,home/data/b.mbtiles"

But I always got the error. When I use "mbtiles:/home/data/a.mbtiles,b.mbtiles", 
I got no error but nothing is loaded so my tiles are empty.

I am not sure if this is an issue or simply a wrong notation in the project.yml.

**Comment by mojodna** [comment]
Looks like you found [tilelive-merge](https://github.com/mojodna/tilelive-merge), which is necessary as tilelive-tmstyle (and ultimately Mapnik) can only read from a single vector tile source.
