### ISSUE TITLE
can't use tm2z files?

### ISSUE THREAD

**Issue by heaversm** [mojodna/tessera#26]
Hi - in mapbox studio, I seem to only have the option of exporting a tm2z package (which I assume is just a compressed folder), though most documentation I've read around using tessera revolves around a tm2 file (or mbtiles). When I attempt to use this in tessera:

```tessera tmstyle:///vagrant/mblight.tm2z```

 I get the following:

```
Listening at http://0.0.0.0:8080/

/usr/local/lib/node_modules/tessera/server.js:43
        throw err;
              ^
Error: ENOTDIR, open '/vagrant/mblight.tm2z/project.yml'
```

Is this an issue with the file format, or am I doing something else wrong. Note that I'm trying to use tessera in conjunction with [this](https://github.com/lliss/tile-converter)

which I found via [this article](http://www.azavea.com/blogs/labs/2015/05/converting-mapbox-studio-vector-tiles-to-rasters/)

**Comment by mojodna** [comment]
(This is actually a `tilelive-tmstyle` issue, so moving discussion to https://github.com/mojodna/tilelive-tmstyle/issues/2)
