### ISSUE TITLE
Serving mbtiles, tiles all black

### ISSUE THREAD

**Issue by four43** [mojodna/tessera#29]
I'm trying to serve up mbtiles via: `tessera mbtiles://./0-8z.mbtiles`

I was trying to verify the tiles were created correctly (using the `tl` tool, but that might be a different issue)

The tessera script puked when a tile was fetched, throwing this error for each tile request:

__SOLVED:__  Missing xray
```
GET /_/4/7/7.png 500 1.212 ms - 1231
Error: Invalid tilesource protocol: xray+mbtiles:
    at Object.tilelive.load (/usr/local/lib/node_modules/tilelive/lib/tilelive.js:92:25)
    at /usr/local/lib/node_modules/tessera/node_modules/tilelive-cache/index.js:128:23
    at lock (/usr/local/lib/node_modules/tessera/node_modules/tilelive-cache/node_modules/locking-cache/index.js:57:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/tessera/node_modules/tilelive-cache/index.js:127:12)
    at Object.load (/usr/local/lib/node_modules/tessera/node_modules/tilelive-cache/node_modules/locking-cache/index.js:85:17)
    at /usr/local/lib/node_modules/tessera/lib/app.js:136:21
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/tessera/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/tessera/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/usr/local/lib/node_modules/tessera/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/tessera/node_modules/express/lib/router/layer.js:95:5)
```

Versions of things:
```
$ npm ls -g mapnik
/usr/local/lib
└── mapnik@3.4.7 

$ npm ls -g tessera
/usr/local/lib
└── tessera@0.5.3 

$ npm ls -g | grep tilelive
│ ├─┬ tilelive-cache@0.4.5
│ └── tilelive-modules@0.1.4
├─┬ tilelive@5.9.0
├─┬ tilelive-file@0.0.3
├─┬ tilelive-http@0.8.0
├── tilelive-mapbox@0.4.0
├─┬ tilelive-mapnik@0.6.17
├─┬ tilelive-tmsource@0.4.0
│ ├─┬ tilelive-bridge@1.6.0
├─┬ tilelive-tmstyle@0.4.1
├─┬ tilelive-vector@3.5.0
│ ├─┬ tilelive-cache@0.4.5
│ ├── tilelive-modules@0.1.4
│ └─┬ tilelive-streaming@0.4.0
├─┬ tilelive-xray@0.1.3

```

I still have a problem however, all the generated tiles are black! This was working a while ago, there are so many dependencies however I'm not sure what has changed. The tiles are returned are fine and there are no errors:

```
GET /_/3/5/1.png 200 38.263 ms - 103
```

Any thoughts? Thanks.

**Comment by mojodna** [comment]
xray may be rendering black tiles because there are no features in the underlying vector tile source.

To check, download the corresponding PBF (`/3/5/1.pbf`) and use [`tileinfo`](https://github.com/mapbox/mapnik-vector-tile/tree/master/examples/c%2B%2B) to dump the data in it.

**Comment by four43** [comment]
Having issues compiling mapbox-vector-tile. Looking into it and I'll report back. In the meantime, here is the /3/5/1.pbf: 

https://www.dropbox.com/s/g907claqd4mkxl0/1.pbf?dl=0

**Comment by four43** [comment]
Okay, I was able to get an older version of tileinfo running (https://github.com/mapbox/mapnik-vector-tile/issues/155) and this is what what I found:

```
message: appears not to be compressed
failed to parse protobuf
layers: 0
```

Not super helpful. Layers 0 is concerning. Sounds like your guess was correct. I'll look back at the source project again.

**Comment by mojodna** [comment]
Good find.

There have been some changes over the last year+ in how the tiles are stored. `file 1.pbf` should tell you what the compression format is.  (I can't remember if the current preference is for it to be deflated or gzipped and whether that _must_ happen inside or outside mapnik.  Might also depend on versions.)  Fetching one of the live Mapbox tiles (probably using the network inspector on a GL demo) would allow it to serve as a good reference.

**Comment by four43** [comment]
Thanks for the feedback @mojodna 

So we need a good pbf to compare it with, lets try:

https://a.tiles.mapbox.com/v4/mapbox.streets/3/5/1.png?access_token=pk.eyJ1IjoiZm91cjQzIiwiYSI6ImI1OWozRkkifQ.IBBQqRL7m_rHVpR378z6kg -> PBF

https://a.tiles.mapbox.com/v4/mapbox.streets/3/5/1.pbf?access_token=pk.eyJ1IjoiZm91cjQzIiwiYSI6ImI1OWozRkkifQ.IBBQqRL7m_rHVpR378z6kg

Darn. Mapbox isn't serving pbf info directly for stylized images. Try 2,

I created a project in Mapbox Studio Classic that uses Mapbox as a data source, serving via `tessera`. Images render properly in the browser! Looking great for this project. Using `tmstyle://`

http://localhost:8080/3/5/1.png  - Works great
http://localhost:8080/3/5/1.pbf  - Doesn't work, 404

I'm using the same versions of everything I did yesterday, just this time I'm using tmstyle vs. tmsource.

Try 3, mapbox tiles directly.

`tessera mapbox:///mapbox.mapbox-streets-v5`

http://localhost:8080/3/5/1.png  - Works great
http://localhost:8080/3/5/1.pbf  - Also works, whew

https://www.dropbox.com/s/5vco6vs3e0wa0ke/mapbox.pbf?dl=0 is the Mapbox vector pbf.

`tileinfo` had much more to say:

```
message: appears not to be compressed
layers: 4
water:
  version: 1
  extent: 4096
  features: 6
  keys: 1
  values: 1
  geometry summary:
    total: 3251
    commands: 285
    move_to: 95
    line_to: 1388
    close: 95
    degenerate polygons: 95
    empty geoms: 0
admin:
  version: 1
  extent: 4096
  features: 18
  keys: 4
  values: 4
  geometry summary:
    total: 1464
    commands: 342
    move_to: 171
    line_to: 390
    close: 0
    degenerate polygons: 0
    empty geoms: 0
country_label:
  version: 1
  extent: 4096
  features: 102
  keys: 7
  values: 439
  geometry summary:
    total: 306
    commands: 102
    move_to: 102
    line_to: 0
    close: 0
    degenerate polygons: 0
    empty geoms: 0
marine_label:
  version: 1
  extent: 4096
  features: 20
  keys: 7
  values: 85
  geometry summary:
    total: 204
    commands: 32
    move_to: 20
    line_to: 66
    close: 0
    degenerate polygons: 0
    empty geoms: 0
```

So that is a vector tile that was rendered to raster, right? Is that different than my project which was trying to serve up raster images?

**Comment by mojodna** [comment]
```bash
npm install tessera tilelive-mapbox tilelive-xray
node_modules/.bin/tessera mapbox:///mapbox.mapbox-streets-v5
```

http://localhost:8080/_/3/5/1.png (note the `_` is the PBF rendered to an image using tilelive-xray--without this, I get a 404):

![image](https://cloud.githubusercontent.com/assets/45/10676467/2cf992a4-78bb-11e5-9061-d5ca12e25603.png)

http://localhost:8080/3/5/1.pbf - vector tile

(Sorry for disappearing a couple weeks ago, busy time here.)

**Comment by mojodna** [comment]
Looking into your PBF now.

**Comment by four43** [comment]
Hey it's all good, I forgot this issue was still open. Thanks for taking a look. Let me know if I can help.

**Comment by mojodna** [comment]
Your PBF (https://www.dropbox.com/s/g907claqd4mkxl0/1.pbf?dl=0) appears to actually be a (fully transparent, empty) WebP image.  (I compiled `mapnik-vector-tile@0.9.3` to get `tileinfo`; `master` won't compile for me.)

How did you produce the MBTiles archive that it came from?

Can you dump the TileJSON from it?  Simple way:

```bash
npm install tl mbtiles
node_modules/.bin/tl info mbtiles://./0-8z.mbtiles | jq .
```

(I'm particularly interested in what `format` is, as that dictates the `Content-Type` that tiles are served using.)

**Comment by four43** [comment]
@mojodna - Sorry I've left this open for so long, got caught up on some other stuff.

Let's try this again.

Using mapnik@3.4.9
node@4.2.2
And the latest version of your tl and related packages.

I updated my packages and everything seems to be working now! So whatever little bug I was experiencing has been fixed. Thanks for the help @mojodna 

-Seth

**Comment by glarrain** [comment]
Hi @four43. By
> Using mapnik@3.4.9

Do you mean this?
> Using mapnik@3.0.9
