### ISSUE TITLE
"Invalid index file" for shapefiles

### ISSUE THREAD

**Issue by aaronblondeau** [mojodna/tessera#37]
Using tilelive-carto on a map style that uses these shapefiles :
http://tile.openstreetmap.org/processed_p.tar.bz2
http://tile.openstreetmap.org/shoreline_300.tar.bz2
http://tile.openstreetmap.org/world_boundaries-spherical.tgz
tessera returns "Error: Invalid index file".  After determining that the error was related to shapefiles by  tracking down the message origin in mapnik's shape.input file, I was able to resolve it by removing the .index files.

This is most likely an issue with mapnik itself, but a more detailed description of the issue would be needed before reporting there.  I have attached a small TillMill project that demonstrates the issue.  Run the get-shapefiles.sh script before loading with tessera.

[TesseraDebug.zip](https://github.com/mojodna/tessera/files/89463/TesseraDebug.zip)

**Comment by mojodna** [comment]
It's definitely an issue with Mapnik itself. I'd recommend trying to generate some images using `nik2img.py` (bundled with Mapnik core) to see if the same errors arise.

You can also narrow it to specific versions of Mapnik (or node-mapnik, which bundle specific versions of Mapnik core) by `npm install mapnik@3.4.<whatever>`.

**Comment by aaronblondeau** [comment]
That's what I thought - I'll do some more research and report on mapnik if I can get the issue isolated.

**Comment by mojodna** [comment]
@almccon and I recently ran into this. It appears that somewhere in the mapnik-3.4 series the index file format has changed (we were reproducing it with 3.4.16).

We managed to solve it by using the `shapeindex` alternative that now ships with node-mapnik: `node_modules/.bin/mapnik-shapeindex.js`
