### ISSUE TITLE
404s include upstream headers (which make them invalid)

### ISSUE THREAD

**Issue by steve9164** [mojodna/tessera#38]
I'm using Tessera as a web server for Mapbox vector tiles tiles generated from a shapefile using tilelive-bridge. Tessera throws 404 errors when requesting tiles with no geometry. What is the best way to suppress these 404 errors (so that the client doesn't keep trying to download these tiles and so the broswer debugger isn't filled with 404s)?

I've thought of 2 ways, but I'm not sure if there is a better way:
- Make a new tilelive module that calls tilelive-bridge functions, but returns an empty tile instead of null if there is no geometry but the tile is still within the bbox
- Modify Tessera to return empty tile on an error from source if the tile is within the source bbox

**Comment by mojodna** [comment]
This is by design. Leaflet (etc.) is going to request the tiles no matter what (within a bbox), so we've discovered that it's actually faster (and marginally smaller) for the response to be a 404 than to return a transparent (or solid-color) image and have it pass through the browser's image decoder pipeline.

Think of the 404s as marking when potential speed-ups are occurring ;-) (Yeah, having them show up as errors in the console is a bummer.)

**Comment by steve9164** [comment]
@mojodna Thanks for the reply. I seem to be getting malformed 404 errors from Tessera. They say they are gzipped: 

> $ curl -I http://127.0.0.1:8000/FID_TM_WORLD_BORDERS/6/49/35.pbf
HTTP/1.1 404 Not Found
Access-Control-Allow-Origin: *
Content-Type: application/x-protobuf; charset=utf-8
content-encoding: gzip
x-tilelive-contains-data: true
Content-Length: 9
ETag: W/"9-ngdvWIX1zBakta643krf9Q"
X-Response-Time: 4.049ms
Date: Fri, 29 Jan 2016 06:30:25 GMT
Connection: keep-alive

But they aren't. They're just the 9 bytes `Not found`. This is causing `net::ERR_CONTENT_DECODING_FAILED` errors in Chrome console.

**Comment by mojodna** [comment]
Good find. If you want to take a whack at a PR (I might get to this next week), the relevant code is here:

https://github.com/mojodna/tessera/blob/master/lib/app.js#L223-L228

`res.set(headers)` should only happen when returning 200s.

**Comment by mojodna** [comment]
Uh, it was a one-liner, so I went ahead and did it. I'll release v0.6.1 soon.

**Comment by mojodna** [comment]
Published in v0.6.1 this evening.
