### ISSUE TITLE
Does not work with tmstyle project that works with kosmtik

### ISSUE THREAD

**Issue by rory** [mojodna/tessera#42]
I am trying to "port" the [openstreetmap-carto style](https://github.com/gravitystorm/openstreetmap-carto) to vector tiles, and I've quickly hacked something together so that that repo can act as a tm2source and a tmstyle. I can serve the pbf tiles with tessera, or generate a mbtiles with `tl` (and serve that mbtiles with tessera too).

The style can be loaded and viewed when using [kosmtik](https://github.com/kosmtik/kosmtik), but not when using tessera.

Getting this error when I try to use it.

    $ tessera -p 8081 tmstyle://./
    Listening at http://0.0.0.0:8081/
    
    /usr/lib/node_modules/tilelive-tmstyle/node_modules/async/lib/async.js:51
            if (arr.map) {
                   ^
    TypeError: Cannot read property 'map' of undefined
        at _map (/usr/lib/node_modules/tilelive-tmstyle/node_modules/async/lib/async.js:51:16)
        at _asyncMap (/usr/lib/node_modules/tilelive-tmstyle/node_modules/async/lib/async.js:234:15)
        at Object.map (/usr/lib/node_modules/tilelive-tmstyle/node_modules/async/lib/async.js:216:23)
        at /usr/lib/node_modules/tilelive-tmstyle/index.js:90:18
        at fs.js:266:14
        at /usr/lib/node_modules/tilelive-vector/node_modules/tar/node_modules/fstream/node_modules/graceful-fs/graceful-fs.js:43:10
        at Object.oncomplete (fs.js:107:15)

**Comment by mojodna** [comment]
Can you share the `project.yml` (or the repo you're working in)?

`data.styles` appears to be undefined (from `project.yml`) in https://github.com/mojodna/tilelive-tmstyle/blob/master/index.js#L90 but I'm not sure why that would be the case.

**Comment by rory** [comment]
> Can you share the project.yml (or the repo you're working in)?

Here it is:

    scale: 1
    metatile: 1
    name: "OpenStreetMap Carto"
    description: "A faithful reimplementation of the standard OpenStreetMap style"
    bounds: &world
      - -180
      - -85.05112877980659
      - 180
      - 85.05112877980659
    center:
      - 0
      - 0
      - 4
    format: "png"
    interactivity: false
    minzoom: 0
    maxzoom: 22
    srs: "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over"
    source: 'tilejson+http://localhost:8080/index.json'
    layers:
      - world
      - coast-poly
      - builtup
      - necountries
      - landcover-low-zoom
      - landcover
      - landcover-line
      - water-lines-casing
      - water-lines-low-zoom
      - icesheet-poly
      - water-areas
      - landcover-area-symbols
      - icesheet-outlines
      - water-lines
      - water-barriers-line
      - water-barriers-poly
      - marinas-area
      - piers-poly
      - piers-line
      - water-barriers-point
      - bridge
      - buildings
      - buildings-major
      - tunnels
      - citywalls
      - landuse-overlay
      - line-barriers
      - cliffs
      - area-barriers
      - ferry-routes
      - turning-circle-casing
      - highway-area-casing
      - highway-area-fill
      - roads-fill
      - turning-circle-fill
      - aerialways
      - roads-low-zoom
      - waterway-bridges
      - bridges
      - guideways
      - admin-mid-zoom
      - admin-high-zoom
      - power-minorline
      - power-line
      - nature-reserve-boundaries
      - tourism-boundary
      - trees
      - placenames-large
      - placenames-medium
      - placenames-small
      - stations
      - stations-poly
      - amenity-points-poly
      - amenity-points
      - power-towers
      - power-poles
      - roads-text-ref-low-zoom
      - junctions
      - bridge-text
      - roads-text-ref
      - roads-area-text-name
      - roads-text-name
      - paths-text-name
      - text-poly-low-zoom
      - text-poly
      - text-line
      - text-point
      - building-text
      - interpolation
      - housenumbers
      - housenames
      - water-lines-text
      - ferry-routes-text
      - admin-text
      - nature-reserve-text
      - amenity-low-priority
      - amenity-low-priority-poly
    Stylesheet:
      - "style.mss"
      - "shapefiles.mss"
      - "landcover.mss"
      - "water.mss"
      - "water-features.mss"
      - "roads.mss"
      - "power.mss"
      - "citywalls.mss"
      - "placenames.mss"
      - "buildings.mss"
      - "stations.mss"
      - "amenity-points.mss"
      - "ferry-routes.mss"
      - "aerialways.mss"
      - "admin.mss"
      - "addressing.mss"

> data.styles appears to be undefined (from project.yml) in https://github.com/mojodna/tilelive-tmstyle/blob/master/index.js#L90 but I'm not sure why that would be the case.

That appears to have fixed it. When I changed `Stylesheets` to `styles`, that error goes away. And now I get an error about fonts (ah mapnik and fonts...)

**Comment by mojodna** [comment]
Good find. Fixed and published as v0.5.1.

TileMill projects use `Stylesheet` as the key for the list of MSS files. Mapbox Studio Classic (TM2) uses `styles` and internally translates it to `Stylesheet` when writing out configurations. kosmtik's approach is certainly more consistent.

`MAPNIK_FONT_PATH` may be helpful, as might adding `font-dir: url("fonts/");` inside a `Map` CartoCSS declaration.

Tessera doesn't configure Mapnik to register system-level fonts by design, as it's too easy to end up distributing stylesheets that rely on globally-installed fonts.
