### ISSUE TITLE
Is it possible to server vector tile within a .mbtiles file?

### ISSUE THREAD

**Issue by haoliangyu** [mojodna/tessera#58]
MBTiles supports vector tile and I wonder if tessera works with .mbtiles file with vector tiles.

**Comment by jingsam** [comment]
```
npm install -g mbtiles
tessera mbtiles://./whatever.mbtiles
```
Please read [README.md](https://github.com/mojodna/tessera)

**Comment by mojodna** [comment]
It does.

Thanks @jingsam!

**Comment by haoliangyu** [comment]
Thank you for clarifying this!
