### ISSUE TITLE
serve multi datasource in a directory 

### ISSUE THREAD

**Issue by beyoung** [mojodna/tessera#61]
for tessera now ,it only serves datasource in the config file or datasource specified when we start server, i think if i can config a directory which contains many datasource then i can dynamic copy datasource into the directory would make tessera more powerful.

**Comment by mojodna** [comment]
`conf.d`-style directories are supported:

> If `--config` is set to a directory, all JSON files in it will be concatenated together to form a single configuration. In the case of repeated options or paths, the last one will win (where files are loaded in alphabetical order).

**Comment by beyoung** [comment]
@mojodna  THX.

**Comment by beyoung** [comment]
@mojodna  by the way ,i want to know that can tessera serve data on the fly? or must i specify datasource when i start server ?
