### ISSUE TITLE
Exits without doing anything on tmsource

### ISSUE THREAD

**Issue by pnorman** [mojodna/tessera#65]
when I do
```sh
npm install mapnik tilelive-tmsource tilelive-tmstyle tilejson tilelive-http tilelive-vector tessera
node_modules/tessera/server.js tmsource://./
```
nothing happens and tessera immediately exits with exit code 0.

I also tried `node_modules/tessera/server.js tmsource:///home/pnorman/osm/meddo` and `PATH=`pwd`/node_modules/.bin/:$PATH node_modules/tessera/server.js tmsource://./`, nothing changed.

**Comment by mojodna** [comment]
`server.js` exports a function rather than being the main command entrypoint.

Try `node_modules/.bin/tessera tmsource://./` instead.

**Comment by mojodna** [comment]
(`node_modules/.bin/tessera` is https://github.com/mojodna/tessera/blob/master/bin/tessera.js, marked as the package binary in https://github.com/mojodna/tessera/blob/master/package.json#L6)
