### ISSUE TITLE
Serving up PNG file?

### ISSUE THREAD

**Issue by ianhuynh** [mojodna/tessera#74]
I have PNG file with geometry inside -- is there a way to get tessera to serve it up as tile?

**Comment by mojodna** [comment]
If [mapnik-omnivore](https://github.com/mapbox/mapnik-omnivore) understands world files (the `.pngw` part), then [`tilelive-omnivore`](https://github.com/mapbox/tilelive-omnivore) should work.

It looks like it doesn't (but it might?), so you could convert it to a GeoTIFF w/ embedded georeferencing (vs. a `.tfw`) and use that.

**Comment by ianhuynh** [comment]
@mojodna : thanks will try that route.   I was able to get gdal_translate to convert a GeoTiff to mbtiles -- however, the quality looks to be pretty poor - something must have happened during the conversion.

**Comment by ianhuynh** [comment]
@mojodna :  I was able to use GeoTiff source and convert GeoTiff to mbtiles via gdal packages.  The MBtiles format is 'PNG' not 'PBF'

```
  basename: 'texas.mbtiles',
  id: 'texas',
  filesize: 393216,
  name: 'texas',
  type: 'overlay',
  description: 'texas',
  version: '1.1',
  format: 'png',  <<<< FORMAT IS NOT PBF
  bounds: 
   [ -7.759181279115034,
     7.463407937286124,
     -3.098231572083783,
     10.70395710376009 ],
  maxzoom: 9,
  minzoom: 6,
  center: [ -5.428706425599408, 9.083682520523107, 7 ] }
```


looking through the code  https://github.com/mojodna/tessera/blob/master/server.js , starting at line 144 is where the tile is loaded.   But on line 120, it specifically checks for "pbf" and ignore any other format?

**Comment by mojodna** [comment]
The PBF-specific check is to enable additional functionality for vector tiles ("x-ray", which provides a raster view of the data contained inside it).

The MBTiles format being `PNG`  is totally right. Does this work now?

**Comment by ianhuynh** [comment]
Xray mode works if i just hit  http://localhost:8080/tiles/texas .  Xray is leaflet by default

if u use configuration file driven method , i always get 404 .  our front-end is using mapbox-gl.js client 

```
{
  "/tiles/texas": {
    "source": "mbtiles://./mbtiles/analytics/texas.mbtiles",
    "headers": {
      "Cache-Control": "public,max-age={{#tileJSON}}86400{{/tileJSON}}{{#tile}}3600{{/tile}}",
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "GET",
      "x-tile-path": "/{z}/{x}/{y}.{format}",
      "Surrogate-Control": "max-age=86400"
    }
  }
}

```

**Comment by ianhuynh** [comment]
sorry -- just discovered that we messed up on our side with perhaps bad projection code in the GeoTiff.  It is serving up PNG tiles as expected.   Sorry for the confusion.

**Comment by mojodna** [comment]
No worries, glad it's working!
