### ISSUE TITLE
Cannot serve mbtiles

### ISSUE THREAD

**Issue by boldtrn** [mojodna/tessera#75]
I was playing around with tessera and wanted to serve .mbtiles. I am on Ubuntu 14.04.

```
npm install -g tessera
npm install -g mbtiles
tessera mbtiles://./berlin.mbtiles
```

I get an error:
```
Error: Cannot find module '/usr/lib/node_modules/tessera/node_modules/mapnik/lib/binding/mapnik_settings.js'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/tessera/node_modules/mapnik/lib/mapnik.js:8:16)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

Do I need to configure anything else?

**Comment by mojodna** [comment]
No, this should work, barring other problems (which it looks like you're running into).

One of tessera's dependencies (mapnik) didn't install properly. Try reinstalling tessera (`npm uninstall -g tessera && npm install -g tessera`). What version of Node are you using? (`node --version`) If there are error messages in the installation log, please post them here.

Even if installation works, you may run into a different issue (since you're on Ubuntu 14.04) where you'll get an error about GLIBC. To fix that, run:

```bash
add-apt-repository -y ppa:ubuntu-toolchain-r/test
apt-get update
apt-get install -y libstdc++6
```

**Comment by boldtrn** [comment]
Thanks this solved it for me. I also needed to install `libstdc++6` but now I can start the server and serve .pbf files.

I was actually hoping to server mvt instead of pbf. Is this possible or do I need a different data source? This might also be a different issue, let me know if you want to discuss this somewhere else.

Sorry if this has been asked before, I could not find any relevant issues.

**Comment by mojodna** [comment]
PBFs are MVTs, so the data source will be the same. Are you referring to changing the extension served up? It's a global thing based on the content-type of the MBTiles archive (or generating source). Might be time to change it up to match Mapbox et al.

**Comment by boldtrn** [comment]
@mojodna ah ok, thanks. I was using VTM to visualize the tiles, but I couldn't make it work and debugging pbfs is not really easy (at least for me). I assume that there an issue with some layernames or tag names, will fiddle around a bit and see if I can make it work.
