### ISSUE TITLE
externalize processStaticMap -> abaculus -> mapnik

### ISSUE THREAD

**Issue by indus** [mojodna/tessera#86]
I had the same build issue like #66.
After having a look what mapnik is used for it seems to me that I won't use the "staticMap" functionality and therefor wouldn't even need abaculus and mapnik.
Because of the issues that might arise from including a dependency with a build step, the size of this dependency and the uncertain use of the functionality I would wish that it gets provided as an optional extension or plugin.

**Comment by mojodna** [comment]
Agreed; I just created [lambda-tileserver](https://github.com/mojodna/lambda-tileserver) for a related reason. Would you be willing to put together a PR stripping out functionality that uses Mapnik?

It's straightforward enough that another tile server could be easily assembled that includes tessera and adds the static map generation functionality; see https://github.com/stamen/toner-carto/blob/master/server.js for a server that wraps tessera w/ error reporting capabilities.

**Comment by indus** [comment]
Removing these parts should be easy and I can make a PR for that but building a plugin, witch would require a new repo (?), Is more complicated...Am 18.11.2018 2:51 vorm. schrieb Seth Fitzsimmons <notifications@github.com>:Agreed; I just created lambda-tileserver for a related reason. Would you be willing to put together a PR stripping out functionality that uses Mapnik?
It's straightforward enough that another tile server could be easily assembled that includes tessera and adds the static map generation functionality; see https://github.com/stamen/toner-carto/blob/master/server.js for a server that wraps tessera w/ error reporting capabilities.

**Comment by mojodna** [comment]
Published as v0.14.0. I added a note to the README recommending people use `~0.13.1` if they need static map functionality. If sufficient changes are made to tessera, we can revisit creating a server / plugin that wraps it, but for now, that seems like a reasonable solution.
