### ISSUE TITLE
Can I rasterize a custom mapbox gl style with mapbox vector tiles?

### ISSUE THREAD

**Issue by Jeffrey04** [mojodna/tessera#88]
I have a mapbox studio classic serving mapbox vector tiles, and it is styled by a custom in house mapbox gl style (the new stylesheet in JSON). The point of doing this is to also serve users running legacy mapping software without us maintaining two different maps. After spending time setting up tessera (kept failing so I am running it with docker https://hub.docker.com/r/iosphere/tessera ), I get the preview app running and serving rasterized image tiles. However, is there a way I can get it to load the map according to how I style it in the new mapbox gl style format?

Also found this in one of the issues here, is this something I need? https://github.com/trailbehind/tilelive-gl

**Comment by Jeffrey04** [comment]
Looks like I found the answer to most of my questions here, but need a bit of clarification

1. So tessera is moving away from tile renderer, does that mean from 0.14.x onwards there will be no way to achieve what I am hoping for? The docker image that I am using right now is running 0.12, which is doing fine after spending a whole day setting it up properly.
2. After fixing the json file found in this github issue https://github.com/mapbox/mapbox-gl-native/issues/4922#issuecomment-218326791 my map is finally showing image tiles styled with the supplied stylesheet.
3. `tilelive-gl` requires `--require` flag to function properly
```
tessera --require tile-gl gl:///path/to/the/style.json
```

**Comment by mojodna** [comment]
Fantastic, I'm glad things are working!

@JesseCrocker would know more about the `--require` flag; what was the stack trace without it?

> So tessera is moving away from tile renderer, does that mean from 0.14.x onwards there will be no way to achieve what I am hoping for?

Not at all. Tessera has moved away from including Mapnik as a direct dependency (which was used for arbitrarily sized static map generation, not tiles, in which case `tilelive-mapnik` pulls it in), since that has historically complicated tessera installation. Tile rendering very much remains within Tessera's purview.

**Comment by JesseCrocker** [comment]
`--require tilelive-gl` is needed because tilelive gl isn't included in https://github.com/mojodna/tilelive-modules/blob/master/index.json It seems like it could be included there, but i hadnt thought to open a PR for it because i have a bunch of other custom modules i load.

**Comment by mojodna** [comment]
@Jeffrey04 did the actual command include `--require tile-gl` or `--require tilelive-gl`?

I'll go ahead and update tilelive-modules anyway.

**Comment by Jeffrey04** [comment]
> Fantastic, I'm glad things are working!
> 
> @JesseCrocker would know more about the `--require` flag; what was the stack trace without it?

It's OK, not complaining, just jotting down as a note there. Yea, getting everything to set up properly is kinda frustrating (hence the use of that docker image).

> 
> Not at all. Tessera has moved away from including Mapnik as a direct dependency (which was used for arbitrarily sized static map generation, not tiles, in which case `tilelive-mapnik` pulls it in), since that has historically complicated tessera installation. Tile rendering very much remains within Tessera's purview.

glad to hear that (: So I suppose I can update to 0.14.1 now

> `--require tilelive-gl` is needed because tilelive gl isn't included in https://github.com/mojodna/tilelive-modules/blob/master/index.json It seems like it could be included there, but i hadnt thought to open a PR for it because i have a bunch of other custom modules i load.

LOL the only problem with tilelive-gl is probably which one to require (or does it not matter?) because the one I use is the forked version https://github.com/trailbehind/tilelive-gl

> @Jeffrey04 did the actual command include `--require tile-gl` or `--require tilelive-gl`?
> 
> I'll go ahead and update tilelive-modules anyway.

sorry, I made mistake, yea `tilelive-gl`

**Comment by mojodna** [comment]
You should definitely use the trailbehind fork of tilelive-gl; the version published to npm is fairly outdated (and probably won't be updated by Mapbox).

**Comment by Jeffrey04** [comment]
yes, am using that (:

**Comment by Jeffrey04** [comment]
Just out of curisousity, does tessera support WMS standard?

**Comment by mojodna** [comment]
It does not. There may be a tilelive module somewhere that can proxy tiles from a WMS (exposing it as a tiled endpoint), but I don't know of one off the top of my head.

https://github.com/springmeyer/landspeed.js is a Mapnik-based WMS server, but I don't think it's been worked on in many years.

https://mapproxy.org/ seems to be what most people use as a Swiss Army knife for this.

**Comment by Jeffrey04** [comment]
thanks 👍  (:

**Comment by zeevogels** [comment]
Maybe not a bad idea to add a bit of documentation to the readme to make it clearer how to use tilelive-gl? The npm package doesn't work btw you have to use the trailbehind github one.
