### ISSUE TITLE
Use Custom Style File with Tessera

### ISSUE THREAD

**Issue by souviksankar2013** [mojodna/tessera#98]
I have a mbtiles file and also a style file to use with Maptiler GL (to give in pbf format) that I have generated from maputnik. It has entry like - 

{
  "version": 8,
  "name": "Empty Style",
  "metadata": {"maputnik:renderer": "mbgljs"},
  "sources": {
    "composite": {
      "type": "vector",
      "url": "5_1_india.json"
    }
  },
  "sprite": "",
  "glyphs": "https://orangemug.github.io/font-glyphs/glyphs/{fontstack}/{range}.pbf",
  "layers": [
    {
      "id": "background",
      "type": "background",
      "minzoom": 0,
      "maxzoom": 24,
      "layout": {"visibility": "visible"},
      "paint": {
        "background-opacity": 0.8,
        "background-color": "rgba(166, 250, 255, 1)"
      }
    },
    {
      "id": "world",
      "type": "fill",
      "source": "composite",
      "source-layer": "world_countriesgeojsonl",
      "layout": {"visibility": "visible"},
      "paint": {
        "fill-color": "rgba(22, 114, 147, 1)",
        "fill-outline-color": "rgba(123, 120, 120, 1)",
        "fill-opacity": 0.5
      }
    },
    {
      "id": "soi_fill",
      "type": "fill",
      "source": "composite",
      "source-layer": "india_soigeojsonl",
      "layout": {"visibility": "visible"},
      "paint": {
        "fill-color": "rgba(253, 255, 235, 0.88)",
        "fill-opacity": 1,
        "fill-outline-color": "rgba(152, 149, 149, 1)"
      }
    },
    {
      "id": "Australia",
      "type": "fill",
      "source": "composite",
      "source-layer": "world_countriesgeojsonl",
      "filter": ["any", ["==", "continent", "Oceania"]],
      "layout": {"visibility": "none"},
      "paint": {
        "fill-outline-color": "rgba(164, 160, 160, 1)",
        "fill-opacity": 1,
        "fill-color": "rgba(182, 125, 143, 1)"
      }
    },
    {
      "id": "Africa",
      "type": "fill",
      "source": "composite",
      "source-layer": "world_countriesgeojsonl",
      "filter": ["any", ["==", "continent", "Africa"]],
      "layout": {"visibility": "none"},
      "paint": {
        "fill-outline-color": "rgba(164, 160, 160, 1)",
        "fill-opacity": 1,
        "fill-color": "rgba(247, 175, 157, 1)"
      }
    },
    {
      "id": "Asia",
      "type": "fill",
      "source": "composite",
      "source-layer": "world_countriesgeojsonl",
      "filter": ["all", ["==", "continent", "Asia"]],
      "layout": {"visibility": "none"},
      "paint": {
        "fill-outline-color": "rgba(164, 160, 160, 1)",
        "fill-opacity": 1,
        "fill-color": "rgba(97, 209, 160, 0.16)"
      }
    },
    {
      "id": "Antartica",
      "type": "fill",
      "source": "composite",
      "source-layer": "world_countriesgeojsonl",
      "filter": ["all", ["==", "continent", "Antarctica"]],
      "layout": {"visibility": "none"},
      "paint": {
        "fill-outline-color": "rgba(164, 160, 160, 1)",
        "fill-opacity": 1,
        "fill-color": "rgba(255, 250, 250, 1)"
      }
    }
],
  "id": "9h91wwjmi"
}

When I put the same mbtiles in tessera to serve the tiles in png the style changes in black background. How to use this style file with my mbtiles in tessera?

**Comment by mojodna** [comment]
The PNG display for Mapbox Vector Tiles uses https://github.com/mojodna/tilelive-xray to rasterize the tiles, which is why they have black backgrounds. If you want rasterized version of Mapbox GL / MapLibre styles, check out [TileServer GL](https://github.com/maptiler/tileserver-gl).
